# Generated by Django 2.1.1 on 2018-09-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('input_numbers', models.PositiveIntegerField()),
                ('inverse', models.BooleanField()),
                ('its_and', models.BooleanField()),
                ('picture', models.ImageField(upload_to='elements/')),
                ('description', models.TextField()),
            ],
        ),
    ]
