# Generated by Django 2.1.1 on 2018-09-13 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palevo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='semestr',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='prepod',
            new_name='teacher',
        ),
    ]
